spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3308/testdb?useSSL=false
    username: root
    password: andand
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
#for h2
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 60000
